---
galaxy_info:
  author: Felipe Faria
  description: Instalação do Docker Compose no Linux
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - docker
    - compose
    - containers
    - devops
dependencies: []
